# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/919970b3-3c44-4e77-abcf-dda36978a95e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-54b3cada-9765-4ee6-a6b1-7cce7672954d".device = "/dev/disk/by-uuid/54b3cada-9765-4ee6-a6b1-7cce7672954d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C893-5FB9";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/33d720a5-3c34-4efa-84b6-6e8f341e4ade ";
        encrypted = {
          enable = true;
          label = "swap";
          blkDev = "/dev/disk/by-uuid/6e4a20c5-57f1-4909-8e5e-4b118e09c50e";
        };
     }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
